apiVersion: v1
kind: Pod
metadata:
  name: nextflow-log-analyzer
spec:
  containers:
  - name: main
    image: nextflow:perf # perf fork nextflow image
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    workingDir: /input
    volumeMounts:
      - mountPath: /input
        name: input
      - mountPath: /workdir
        name: data
      - mountPath: /notebook
        name: notebook
    securityContext:
      runAsUser: 0
  volumes:
  - name: input
    persistentVolumeClaim:
      claimName: pvc-input
  - name: data
    persistentVolumeClaim:
      claimName: pvc-work
  - name: notebook
    persistentVolumeClaim:
      claimName: pvc-notebook