kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextflow-pod-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods","pods/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextflow-pod-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: nextflow
    namespace: default
roleRef:
  kind: Role
  name: nextflow-pod-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: nextflow
  namespace: default