kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nextflow-cluster 
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: <local-path>
        containerPath: /host-data
  - role: worker
    extraMounts:
      - hostPath: <local-path>
        containerPath: /host-data
  - role: worker
    extraMounts:
      - hostPath: <local-path>
        containerPath: /host-data